spring:
  application:
    name: zerotrace-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/zerotrace}
    username: ${SPRING_DATASOURCE_USERNAME:zerotrace}
    password: ${SPRING_DATASOURCE_PASSWORD:zerotrace}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  error:
    include-message: always

